# Generated by Django 5.2.1 on 2025-05-22 XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        # Agregar los nuevos campos para Interesado
        migrations.AddField(
            model_name='interesado',
            name='apellido_paterno',
            field=models.CharField(max_length=50, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interesado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),

        # Agregar los nuevos campos para Reclutador
        migrations.AddField(
            model_name='reclutador',
            name='apellido_paterno',
            field=models.CharField(max_length=50, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclutador',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),

        # Eliminar los campos antiguos de apellidos
        migrations.RemoveField(
            model_name='interesado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='reclutador',
            name='apellidos',
        ),
    ]